language: java

jdk:
  - openjdk11

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean build --continue

sudo: required

services:
  - docker
