exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy

sass:
  style: compressed

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/arakelian/jekyll-theme-gerbera"

remote_theme: benbalter/retlab
#remote_theme: arakelian/jekyll-theme-gerbera

jekyll_tidy:
    compress_html: true
    ignore_env: development    

markdown: kramdown
highlighter: rouge


title:    docker-junit-rule
tagline:  JUnit Rule for creating reusable Docker containers that live across JUnit test clases
version:  1.5.1
author: Greg Arakelian
email: greg@arakelian.com

description: >
   JUnit Rule for starting and stop Docker containers as part of a JUnit test case.


# see: https://jekyllrb.com/docs/permalinks/
permalink:        /:categories/:year/:month/:day/:title/

collections:
  examples:
    order: 2
    title: "Examples"
    output: true
  posts:
    order: 3
    title: "Blog"
    indexPage: "/blog/"
    permalink:    /blog/:categories/:year/:month/:day/:title
